import { NgModule, ModuleWithProviders } from '@angular/core';
import {
    AdErrorCollectModule,
    AdFooterToolbarModule,
    AdSidebarNavModule,
    AdDownFileModule,
    AdImageModule,
    AdAvatarListModule,
    AdDescListModule,
    AdEllipsisModule,
    AdGlobalFooterModule,
    AdExceptionModule,
    AdNoticeIconModule,
    AdNumberInfoModule,
    AdPageHeaderModule,
    AdResultModule,
    AdStandardFormRowModule,
    AdTagSelectModule,
    AdTrendModule,
    AdCountDownModule,
    AdSimpleTableModule,
   // AdReuseTabModule,
    AdFullContentModule,
    AdXlsxModule,
    AdZipModule,
    AdNumberToChineseModule,
    AdLodopModule,
    AdQuickMenuModule,
  //  AdQRModule,
    // charts
    AdG2BarModule,
    AdG2CardModule,
    AdG2ChartModule,
    AdG2GaugeModule,
    AdG2MiniAreaModule,
    AdG2MiniBarModule,
    AdG2MiniProgressModule,
    AdG2PieModule,
    AdG2RadarModule,
    AdG2TagCloudModule,
    AdG2TimelineModule,
    AdG2WaterWaveModule
} from '@delon/abc'

const MODULES = [
    AdErrorCollectModule,
    AdFooterToolbarModule,
    AdSidebarNavModule,
    AdDownFileModule,
    AdImageModule,
    AdAvatarListModule,
    AdDescListModule,
    AdEllipsisModule,
    AdGlobalFooterModule,
    AdExceptionModule,
    AdNoticeIconModule,
    AdNumberInfoModule,
    AdPageHeaderModule,
    AdResultModule,
    AdStandardFormRowModule,
    AdTagSelectModule,
    AdTrendModule,
    AdCountDownModule,
    AdSimpleTableModule,
    //AdReuseTabModule,
    AdFullContentModule,
    AdXlsxModule,
    AdZipModule,
    AdNumberToChineseModule,
    AdLodopModule,
    AdQuickMenuModule,
   // AdQRModule,
    // charts
    AdG2BarModule,
    AdG2CardModule,
    AdG2ChartModule,
    AdG2GaugeModule,
    AdG2MiniAreaModule,
    AdG2MiniBarModule,
    AdG2MiniProgressModule,
    AdG2PieModule,
    AdG2RadarModule,
    AdG2TagCloudModule,
    AdG2TimelineModule,
    AdG2WaterWaveModule,
  ];
  
  // endregion
  @NgModule({
    imports: [
      AdErrorCollectModule.forRoot(),
      AdFooterToolbarModule.forRoot(),
      AdSidebarNavModule.forRoot(),
      AdDownFileModule.forRoot(),
      AdImageModule.forRoot(),
      AdAvatarListModule.forRoot(),
      AdDescListModule.forRoot(),
      AdEllipsisModule.forRoot(),
      AdExceptionModule.forRoot(),
      AdExceptionModule.forRoot(),
      AdNoticeIconModule.forRoot(),
      AdNumberInfoModule.forRoot(),
      AdPageHeaderModule.forRoot(),
      AdResultModule.forRoot(),
      AdStandardFormRowModule.forRoot(),
      AdTagSelectModule.forRoot(),
      AdTrendModule.forRoot(),
      AdCountDownModule.forRoot(),
      AdSimpleTableModule.forRoot(),
      //AdReuseTabModule.forRoot(),
      AdFullContentModule.forRoot(),
      AdXlsxModule.forRoot(),
      AdZipModule.forRoot(),
      AdNumberToChineseModule.forRoot(),
      AdLodopModule.forRoot(),
      AdQuickMenuModule.forRoot(),
     // AdQRModule.forRoot(),
      // charts
      AdG2BarModule.forRoot(),
      AdG2CardModule.forRoot(),
      AdG2ChartModule.forRoot(),
      AdG2GaugeModule.forRoot(),
      AdG2MiniAreaModule.forRoot(),
      AdG2MiniBarModule.forRoot(),
      AdG2MiniProgressModule.forRoot(),
      AdG2PieModule.forRoot(),
      AdG2RadarModule.forRoot(),
      AdG2TagCloudModule.forRoot(),
      AdG2TimelineModule.forRoot(),
      AdG2WaterWaveModule.forRoot(),
    ],
    exports: MODULES,
  })
  export class DelonABCRootModule {}
  
  @NgModule({ exports: MODULES })
  export class DelonABCModule {
    static forRoot(): ModuleWithProviders {
      return { ngModule: DelonABCRootModule };
    }
  }